replicaCount: 1

image:
  repository: ghcr.io/dpollack/audio-recorder
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  port: 8080

gateway:
  httproute:
    create: false
    hostname: audio-recorder.cluster.lan
    parentRef:
      name: traefik-gateway
      namespace: traefik
      sectionName: ""
