apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "audio-recorder.fullname" . }}
  labels: {{- include "audio-recorder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "audio-recorder.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "audio-recorder.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "audio-recorder.fullname" . }}
      containers:
        - name: audio-recorder
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: LEPTOS_SITE_ROOT
              value: site
            - name: LEPTOS_SITE_ADDR
              value: "0.0.0.0:8080"
            - name: RUST_LOG
              value: info
